import { Figtree } from "next/font/google";
import { twMerge } from "tailwind-merge";
import Sidebar from "@/components/Sidebar";
import SupabaseProvider from "@/context/SupabaseProvider";
import UserProvider from "@/context/UserProvider";
import AuthModal from "@/components/AuthModal";
import UploadSongModal from "@/components/UploadSongModal";
import ToastWrapper from "@/components/ToastWrapper";
import getCurrentUserSongs from "@/serverActions/getCurrentUserSongs";
import "./globals.css";

const figtree = Figtree({subsets: ["latin"]});

export const metadata = {
  title: "Spotify Clone",
  description: "Generated by create next app"
};

export const revalidate = 0;

interface Props {
  children: React.ReactNode
};

const RootLayout = async ({children}: Props) => {
  const currentUserSongs = await getCurrentUserSongs()

  return (
    <html lang="en">
      <body className={twMerge("flex gap-2 w-full h-screen m-0 p-2 text-white bg-black", figtree.className)}>
        <SupabaseProvider>
          <UserProvider>
            <AuthModal />
            <UploadSongModal />
            <Sidebar userSongs={currentUserSongs}/>
            <main className="w-full h-full">
              {children}
            </main>
            <ToastWrapper />
          </UserProvider>
        </SupabaseProvider>
      </body>
    </html>
  )
};

export default RootLayout;