import { Figtree } from "next/font/google";
import { twMerge } from "tailwind-merge";
import Sidebar from "@/components/Sidebar";
import SupabaseProvider from "@/supabase/SupabaseProvider";
import UserProvider from "@/context/UserProvider";
import "./globals.css";

const figtree = Figtree({subsets: ["latin"]});

export const metadata = {
  title: "Spotify Clone",
  description: "Generated by create next app"
};

interface Props {
  children: React.ReactNode
};

const RootLayout = ({children}: Props) => {
  return (
    <html lang="en">
      <body className={twMerge("flex gap-2 w-full h-screen m-0 p-2 text-white bg-black", figtree.className)}>
        <SupabaseProvider>
          <UserProvider>
            <Sidebar/>
            <main className="w-full h-full">
              {children}
            </main>
          </UserProvider>
        </SupabaseProvider>
      </body>
    </html>
  )
};

export default RootLayout;